<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TypeCheckMaterSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('type_check_masters')->insert([
            [
                'question' => '胸やお腹が張って苦しくなることが多い',
                'sort_no' => '1',
                'soul_plus' => '3',
                'soul_minus' => '0',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '1',
                'water_minus' => '0',
                'heat_plus' => '1',
                'heat_minus' => '0',
            ],
            [
                'question' => 'イライラしやすく怒りっぽい',
                'sort_no' => '1',
                'soul_plus' => '3',
                'soul_minus' => '0',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '1',
                'water_minus' => '0',
                'heat_plus' => '1',
                'heat_minus' => '0',
            ],
            [
                'question' => '不眠になりやすい',
                'sort_no' => '3',
                'soul_plus' => '3',
                'soul_minus' => '0',
                'blood_plus' => '1',
                'blood_minus' => '3',
                'water_plus' => '0',
                'water_minus' => '2',
                'heat_plus' => '0',
                'heat_minus' => '0',
            ],
            [
                'question' => '皮膚に吹き出物や化膿がよくできる',
                'sort_no' => '4',
                'soul_plus' => '0',
                'soul_minus' => '0',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '0',
                'water_minus' => '0',
                'heat_plus' => '3',
                'heat_minus' => '0',
            ],
            [
                'question' => 'よく尿が濃い黄色になる',
                'sort_no' => '5',
                'soul_plus' => '0',
                'soul_minus' => '0',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '0',
                'water_minus' => '1',
                'heat_plus' => '3',
                'heat_minus' => '0',
            ],
            [
                'question' => '肩がこりやすい',
                'sort_no' => '6',
                'soul_plus' => '3',
                'soul_minus' => '0',
                'blood_plus' => '3',
                'blood_minus' => '0',
                'water_plus' => '1',
                'water_minus' => '0',
                'heat_plus' => '1',
                'heat_minus' => '0',
            ],
            [
                'question' => '唇や歯ぐきの色が紫に近い',
                'sort_no' => '7',
                'soul_plus' => '0',
                'soul_minus' => '0',
                'blood_plus' => '3',
                'blood_minus' => '0',
                'water_plus' => '0',
                'water_minus' => '0',
                'heat_plus' => '0',
                'heat_minus' => '0',
            ],
            [
                'question' => '頭が重く感じられることが多い',
                'sort_no' => '8',
                'soul_plus' => '0',
                'soul_minus' => '1',
                'blood_plus' => '1',
                'blood_minus' => '0',
                'water_plus' => '3',
                'water_minus' => '0',
                'heat_plus' => '1',
                'heat_minus' => '0',
            ],
            [
                'question' => '雨の日や湿度の高い日は体調が悪くなりがち',
                'sort_no' => '9',
                'soul_plus' => '0',
                'soul_minus' => '0',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '3',
                'water_minus' => '0',
                'heat_plus' => '1',
                'heat_minus' => '0',
            ],
            [
                'question' => '皮膚が乾燥してカサカサしている',
                'sort_no' => '10',
                'soul_plus' => '0',
                'soul_minus' => '0',
                'blood_plus' => '1',
                'blood_minus' => '3',
                'water_plus' => '0',
                'water_minus' => '1',
                'heat_plus' => '0',
                'heat_minus' => '0',
            ],
            [
                'question' => '舌のふちがギザギザになっている',
                'sort_no' => '11',
                'soul_plus' => '0',
                'soul_minus' => '3',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '2',
                'water_minus' => '0',
                'heat_plus' => '0',
                'heat_minus' => '1',
            ],
            [
                'question' => '舌のコケがびっしりついて厚みがある',
                'sort_no' => '12',
                'soul_plus' => '0',
                'soul_minus' => '2',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '2',
                'water_minus' => '0',
                'heat_plus' => '2',
                'heat_minus' => '1',
            ],
            [
                'question' => '舌の裏側の静脈が太く膨らんで見える',
                'sort_no' => '13',
                'soul_plus' => '0',
                'soul_minus' => '0',
                'blood_plus' => '3',
                'blood_minus' => '0',
                'water_plus' => '0',
                'water_minus' => '0',
                'heat_plus' => '0',
                'heat_minus' => '1',
            ],
            [
                'question' => '食欲がなく胃もたれしやすい',
                'sort_no' => '14',
                'soul_plus' => '1',
                'soul_minus' => '3',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '0',
                'water_minus' => '0',
                'heat_plus' => '0',
                'heat_minus' => '0',
            ],
            [
                'question' => '下痢や軟便になることがよくある',
                'sort_no' => '15',
                'soul_plus' => '0',
                'soul_minus' => '3',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '2',
                'water_minus' => '0',
                'heat_plus' => '1',
                'heat_minus' => '1',
            ],
            [
                'question' => 'よく腰や膝に疲れや脱力感を感じる',
                'sort_no' => '16',
                'soul_plus' => '0',
                'soul_minus' => '0',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '0',
                'water_minus' => '0',
                'heat_plus' => '0',
                'heat_minus' => '3',
            ],
            [
                'question' => 'むくみを感じることが多い',
                'sort_no' => '17',
                'soul_plus' => '0',
                'soul_minus' => '0',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '2',
                'water_minus' => '0',
                'heat_plus' => '1',
                'heat_minus' => '3',
            ],
            [
                'question' => '髪の毛が細くパサつきやすい',
                'sort_no' => '18',
                'soul_plus' => '0',
                'soul_minus' => '0',
                'blood_plus' => '1',
                'blood_minus' => '3',
                'water_plus' => '0',
                'water_minus' => '0',
                'heat_plus' => '1',
                'heat_minus' => '2',
            ],
            [
                'question' => '目の疲れや乾燥を感じやすい',
                'sort_no' => '19',
                'soul_plus' => '0',
                'soul_minus' => '0',
                'blood_plus' => '0',
                'blood_minus' => '3',
                'water_plus' => '0',
                'water_minus' => '1',
                'heat_plus' => '0',
                'heat_minus' => '0',
            ],
            [
                'question' => '筋肉が痙攣したり、つりやすい',
                'sort_no' => '20',
                'soul_plus' => '1',
                'soul_minus' => '0',
                'blood_plus' => '0',
                'blood_minus' => '3',
                'water_plus' => '0',
                'water_minus' => '1',
                'heat_plus' => '0',
                'heat_minus' => '0',
            ],
            [
                'question' => 'ほてりやのぼせを感じる',
                'sort_no' => '21',
                'soul_plus' => '2',
                'soul_minus' => '0',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '3',
                'water_minus' => '0',
                'heat_plus' => '1',
                'heat_minus' => '0',
            ],
            [
                'question' => '疲労時や夜に手の平や足の裏が熱くなる',
                'sort_no' => '22',
                'soul_plus' => '0',
                'soul_minus' => '0',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '3',
                'water_minus' => '0',
                'heat_plus' => '0',
                'heat_minus' => '0',
            ],
        ]);
    }
}
