<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TypeCheckMaterSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('type_check_masters')->insert([
            [
                'question' => '经常感觉胸闷或腹胀？',
                'sort_no' => '1',
                'soul_plus' => '3',
                'soul_minus' => '0',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '1',
                'water_minus' => '0',
                'heat_plus' => '1',
                'heat_minus' => '0',
            ],
            [
                'question' => '容易烦躁或易怒？',
                'sort_no' => '1',
                'soul_plus' => '3',
                'soul_minus' => '0',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '1',
                'water_minus' => '0',
                'heat_plus' => '1',
                'heat_minus' => '0',
            ],
            [
                'question' => '容易失眠？',
                'sort_no' => '3',
                'soul_plus' => '3',
                'soul_minus' => '0',
                'blood_plus' => '1',
                'blood_minus' => '3',
                'water_plus' => '0',
                'water_minus' => '2',
                'heat_plus' => '0',
                'heat_minus' => '0',
            ],
            [
                'question' => '皮肤容易起痘或化脓？',
                'sort_no' => '4',
                'soul_plus' => '0',
                'soul_minus' => '0',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '0',
                'water_minus' => '0',
                'heat_plus' => '3',
                'heat_minus' => '0',
            ],
            [
                'question' => '尿液经常是深黄色？',
                'sort_no' => '5',
                'soul_plus' => '0',
                'soul_minus' => '0',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '0',
                'water_minus' => '1',
                'heat_plus' => '3',
                'heat_minus' => '0',
            ],
            [
                'question' => '容易肩膀僵硬？',
                'sort_no' => '6',
                'soul_plus' => '3',
                'soul_minus' => '0',
                'blood_plus' => '3',
                'blood_minus' => '0',
                'water_plus' => '1',
                'water_minus' => '0',
                'heat_plus' => '1',
                'heat_minus' => '0',
            ],
            [
                'question' => '唇色和牙龈颜色成紫色？',
                'sort_no' => '7',
                'soul_plus' => '0',
                'soul_minus' => '0',
                'blood_plus' => '3',
                'blood_minus' => '0',
                'water_plus' => '0',
                'water_minus' => '0',
                'heat_plus' => '0',
                'heat_minus' => '0',
            ],
            [
                'question' => '头部经常感觉沉重？',
                'sort_no' => '8',
                'soul_plus' => '0',
                'soul_minus' => '1',
                'blood_plus' => '1',
                'blood_minus' => '0',
                'water_plus' => '3',
                'water_minus' => '0',
                'heat_plus' => '1',
                'heat_minus' => '0',
            ],
            [
                'question' => '雨天或潮湿的天气容易感觉到身体不适？',
                'sort_no' => '9',
                'soul_plus' => '0',
                'soul_minus' => '0',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '3',
                'water_minus' => '0',
                'heat_plus' => '1',
                'heat_minus' => '0',
            ],
            [
                'question' => '皮肤干燥起皮？',
                'sort_no' => '10',
                'soul_plus' => '0',
                'soul_minus' => '0',
                'blood_plus' => '1',
                'blood_minus' => '3',
                'water_plus' => '0',
                'water_minus' => '1',
                'heat_plus' => '0',
                'heat_minus' => '0',
            ],
            [
                'question' => '舌头边缘呈锯齿状？',
                'sort_no' => '11',
                'soul_plus' => '0',
                'soul_minus' => '3',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '2',
                'water_minus' => '0',
                'heat_plus' => '0',
                'heat_minus' => '1',
            ],
            [
                'question' => '舌苔有很厚的苔藓？',
                'sort_no' => '12',
                'soul_plus' => '0',
                'soul_minus' => '2',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '2',
                'water_minus' => '0',
                'heat_plus' => '2',
                'heat_minus' => '1',
            ],
            [
                'question' => '舌下静脉血管粗大？',
                'sort_no' => '13',
                'soul_plus' => '0',
                'soul_minus' => '0',
                'blood_plus' => '3',
                'blood_minus' => '0',
                'water_plus' => '0',
                'water_minus' => '0',
                'heat_plus' => '0',
                'heat_minus' => '1',
            ],
            [
                'question' => '食欲不振且胃部不适？',
                'sort_no' => '14',
                'soul_plus' => '1',
                'soul_minus' => '3',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '0',
                'water_minus' => '0',
                'heat_plus' => '0',
                'heat_minus' => '0',
            ],
            [
                'question' => '经常腹泻和软便？',
                'sort_no' => '15',
                'soul_plus' => '0',
                'soul_minus' => '3',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '2',
                'water_minus' => '0',
                'heat_plus' => '1',
                'heat_minus' => '1',
            ],
            [
                'question' => '经常感到腰部和腿部疲劳无力？',
                'sort_no' => '16',
                'soul_plus' => '0',
                'soul_minus' => '0',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '0',
                'water_minus' => '0',
                'heat_plus' => '0',
                'heat_minus' => '3',
            ],
            [
                'question' => '经常感到浮肿？',
                'sort_no' => '17',
                'soul_plus' => '0',
                'soul_minus' => '0',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '2',
                'water_minus' => '0',
                'heat_plus' => '1',
                'heat_minus' => '3',
            ],
            [
                'question' => '发质细软干枯？',
                'sort_no' => '18',
                'soul_plus' => '0',
                'soul_minus' => '0',
                'blood_plus' => '1',
                'blood_minus' => '3',
                'water_plus' => '0',
                'water_minus' => '0',
                'heat_plus' => '1',
                'heat_minus' => '2',
            ],
            [
                'question' => '眼睛特别容易疲劳和干涩？',
                'sort_no' => '19',
                'soul_plus' => '0',
                'soul_minus' => '0',
                'blood_plus' => '0',
                'blood_minus' => '3',
                'water_plus' => '0',
                'water_minus' => '1',
                'heat_plus' => '0',
                'heat_minus' => '0',
            ],
            [
                'question' => '肌肉容易抽筋和拉伤？',
                'sort_no' => '20',
                'soul_plus' => '1',
                'soul_minus' => '0',
                'blood_plus' => '0',
                'blood_minus' => '3',
                'water_plus' => '0',
                'water_minus' => '1',
                'heat_plus' => '0',
                'heat_minus' => '0',
            ],
            [
                'question' => '经常感觉身体和面部发热？',
                'sort_no' => '21',
                'soul_plus' => '2',
                'soul_minus' => '0',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '3',
                'water_minus' => '0',
                'heat_plus' => '1',
                'heat_minus' => '0',
            ],
            [
                'question' => '疲劳或夜晚时，手心脚心经常发热？',
                'sort_no' => '22',
                'soul_plus' => '0',
                'soul_minus' => '0',
                'blood_plus' => '0',
                'blood_minus' => '0',
                'water_plus' => '3',
                'water_minus' => '0',
                'heat_plus' => '0',
                'heat_minus' => '0',
            ],
        ]);
    }
}
